###################################################################

# Created by write_sdc on Wed Aug 26 23:27:55 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current uA
create_clock [get_ports clk]  -period 4  -waveform {0 2}
set_input_delay -clock clk  -max 0.2  [get_ports clk]
set_input_delay -clock clk  -max 0.2  [get_ports rst]
set_input_delay -clock clk  -max 0.2  [get_ports start]
set_input_delay -clock clk  -max 0.2  [get_ports {a[15]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[14]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[13]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[12]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[11]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[10]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[9]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[8]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[7]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[6]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[5]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[4]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[3]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[2]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[1]}]
set_input_delay -clock clk  -max 0.2  [get_ports {a[0]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[15]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[14]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[13]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[12]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[11]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[10]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[9]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[8]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[7]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[6]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[5]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[4]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[3]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[2]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[1]}]
set_input_delay -clock clk  -max 0.2  [get_ports {b[0]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[15]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[14]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[13]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[12]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[11]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[10]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[9]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[8]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[7]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[6]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[5]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[4]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[3]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[2]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[1]}]
set_output_delay -clock clk  -max 0.2  [get_ports {y[0]}]
set_output_delay -clock clk  -max 0.2  [get_ports done]
